### ISSUE TITLE
"gesang" character missing in 1.html

### ISSUE THREAD

**Issue by gerritbruening** [gerritbruening/texthist#2]
"gesang" does not appear under "Character Lists" for html.1.
@nilsreiter, do you have an explanation for this?
All three versions have one single "gesang" as speaker.

**Comment by nilsreiter** [comment]
For some reason, the spoken words of "gesang" are not recognized as speech (and the reports only contain characters that actually speak). I'll look into it. https://github.com/quadrama/DramaNLP/issues/33

**Comment by gerritbruening** [comment]
Great, thanks!
I close this as duplicate of https://github.com/quadrama/DramaNLP/issues/33.
